# Question: 

"""
You are given two strings s and t.String t is generated by random shuffling string s and then add one more letter at
a random position.Return the letter that was added to t.

"""

# Solution:  
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for char in t:
            if char not in s:
                return char 
            s = s.replace(char,"",1) #1 means to replace first occurence
        